spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect

  datasource:
    url: jdbc:sqlserver://dbcore.cfnxnolyj32y.us-east-1.rds.amazonaws.com:1433;databaseName=dbcore;encrypt=true;trustServerCertificate=true
    username: ${username}
    password: ${password}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher